export type KOCServerUserSettings = {
  "user_settings_version": `${number}`
  "control_user_settings_data.vscript.cam_y_axis_inverted": `${number}`
  "control_user_settings_data.vscript.controller_cam_x_sensitivity": `${number}`
  "control_user_settings_data.vscript.controller_cam_y_sensitivity": `${number}`
  "control_user_settings_data.vscript.controller_rumble_enabled": `${number}`
  "control_user_settings_data.vscript.trigger_sensitivity": `${number}`
  "control_user_settings_data.vscript.ballform_toggle": `${number}`
  "control_user_settings_data.vscript.throw_toggle": `${number}`
  "control_user_settings_data.vscript.pass_toggle": `${number}`
  "control_user_settings_data.vscript.sprint_toggle": `${number}`
  "control_user_settings_data.vscript.hide_spectating_hud_toggle": `${number}`
  "control_user_settings_data.vscript.glide_toggle": `${number}`
  "control_user_settings_data.vscript.curve_throw_direction": `${number}`
  "control_user_settings_data.vscript.left_stick_inner_dead_zone": `${number}`
  "control_user_settings_data.vscript.right_stick_inner_dead_zone": `${number}`
  "control_user_settings_data.vscript.sprint_throw_cancel_delay": `${number}`
  "control_user_settings_data.vscript.initialized": `${number}`
  "presence_user_settings_data.vscript.appear_offline": `${number}`
  "presence_user_settings_data.vscript.crossplay_allowed": `${number}`
  "presence_user_settings_data.vscript.initialized": `${number}`
  "gameplay_user_settings_data.vscript.respawn_tips_enabled": `${number}`
  "gameplay_user_settings_data.vscript.drink_xp_display_enabled": `${number}`
  "gameplay_user_settings_data.vscript.sprint_blur_enabled": `${number}`
  "gameplay_user_settings_data.vscript.ball_warning_thickness": `${number}`
  "gameplay_user_settings_data.vscript.net_perf_summary_enabled": `${number}`
  "gameplay_user_settings_data.vscript.screen_safezone_level": `${number}`
  "gameplay_user_settings_data.vscript.display_mode": `${number}`
  "gameplay_user_settings_data.vscript.display_mode_scarlett_ps5": `${number}`
  "gameplay_user_settings_data.vscript.nic_hash": `${number}`
  "gameplay_user_settings_data.vscript.initialized": `${number}`
  "audio_user_settings_data.vscript.master_music_volume": `${number}`
  "audio_user_settings_data.vscript.match_music_volume": `${number}`
  "audio_user_settings_data.vscript.sfx_volume": `${number}`
  "audio_user_settings_data.vscript.dialog_volume": `${number}`
  "audio_user_settings_data.vscript.announcer_volume": `${number}`
  "audio_user_settings_data.vscript.crowd_volume": `${number}`
  "audio_user_settings_data.vscript.chat_output_volume": `${number}`
  "audio_user_settings_data.vscript.chat_xbox_output_volume": `${number}`
  "audio_user_settings_data.vscript.chat_input_volume": `${number}`
  "audio_user_settings_data.vscript.chat_availability": `${number}`
  "audio_user_settings_data.vscript.push_to_talk_enabled": `${number}`
  "audio_user_settings_data.vscript.subtitles_enabled": `${number}`
  "audio_user_settings_data.vscript.speech_to_text_enabled": `${number}`
  "audio_user_settings_data.vscript.text_to_speech_enabled": `${number}`
  "audio_user_settings_data.vscript.chat_log_text_size": `${number}`
  "audio_user_settings_data.vscript.chat_log_background": `${number}`
  "audio_user_settings_data.vscript.initialized": `${number}`
  "social_user_settings_data.vscript.notification_duration": `${number}`
  "social_user_settings_data.vscript.receive_friend_requests": `${number}`
  "social_user_settings_data.vscript.receive_group_invites": `${number}`
  "social_user_settings_data.vscript.receive_crew_invites": `${number}`
  "social_user_settings_data.vscript.receive_crew_invite_requests": `${number}`
  "social_user_settings_data.vscript.display_notifications": `${number}`
  "social_user_settings_data.vscript.enable_taunts": `${number}`
  "social_user_settings_data.vscript.share_usage_data": `${number}`
  "social_user_settings_data.vscript.initialized": `${number}`
  "velan_login_legal_terms_accepted": `${number}`
  "market_backfilled_day": `${number}`
  "catch_private_server": `${number}`
  "market_backfilled_offers_0": "NULL_OFFER",
  "contracts_viewed_utc_timestamp": `${number}`
  "tracked_contract_def_a": `${number}`
  "tracked_contract_def_b": `${number}`
  "tracked_contract_def_c": `${number}`
  "tracked_contract_def_d": `${number}`
  "tracked_crew": `${number}`
  "contract_viewed_tutrl_0": `${number}`
  "contract_viewed_14_0": `${number}`
  "audio_user_settings_data.vscript.master_volume": `${number}`
  "s09_accessory_seen_player_icon_1": `${number}`
  "s05_accessory_seen_player_icon_1": `${number}`
  "accessory_seen_player_icon_2": `${number}`
  "s06_accessory_seen_player_icon_1": `${number}`
  "accessory_seen_outfits_2": `${number}`
  "s09_accessory_seen_outfits_1": `${number}`
  "s06_accessory_seen_outfits_1": `${number}`
  "accessory_seen_outfits_1": `${number}`
  "s04_accessory_seen_head_1": `${number}`
  "hint_last_hideout_visit_utc": `${number}`
  "s09_accessory_seen_head_1": `${number}`
  "accessory_seen_head_1": `${number}`
  "s09_accessory_seen_hair_1": `${number}`
  "s08_accessory_seen_hair_1": `${number}`
  "accessory_seen_hair_1": `${number}`
  "s02_accessory_seen_glasses_1": `${number}`
  "accessory_seen_glasses_1": `${number}`
  "s05_accessory_seen_gloves_1": `${number}`
  "accessory_seen_gloves_1": `${number}`
  "s07_accessory_seen_gloves_1": `${number}`
  "s09_accessory_seen_gloves_1": `${number}`
  "s06_accessory_seen_gloves_1": `${number}`
  "s08_accessory_seen_gloves_1": `${number}`
  "s04_accessory_seen_gloves_1": `${number}`
  "s03_accessory_seen_gloves_1": `${number}`
  "s02_accessory_seen_gloves_1": `${number}`
  "accessory_seen_glider_1": `${number}`
  "s09_accessory_seen_glider_1": `${number}`
  "s02_accessory_seen_glider_1": `${number}`
  "s06_accessory_seen_glider_1": `${number}`
  "s03_accessory_seen_glider_1": `${number}`
  "s08_accessory_seen_ult_throw_1": `${number}`
  "s05_accessory_seen_ult_throw_1": `${number}`
  "s07_accessory_seen_ult_throw_1": `${number}`
  "s09_accessory_seen_ult_throw_1": `${number}`
  "s02_accessory_seen_ult_throw_1": `${number}`
  "camera_inverse_setting": `${number}`
}